import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Source: original input data, not generated by this pipeline
SOURCE_DIR = os.path.join(BASE_DIR, "data", "source")

# Intermediate: computed matrices passed between pipeline steps
INTERMEDIATE_DIR = os.path.join(BASE_DIR, "data", "intermediate")

# Output: final plots and CSVs
OUTPUT_DIR = os.path.join(BASE_DIR, "data", "output")

# Source files
annotated_liver_path  = os.path.join(SOURCE_DIR, "annot_humanCD45neg.csv")
count_table_human_dir = os.path.join(SOURCE_DIR, "countTable_human")

# Intermediate files
selected_cells_count_dir = os.path.join(INTERMEDIATE_DIR, "selected_cells")
highly_variable_count_dir = os.path.join(INTERMEDIATE_DIR, "hv_counts_cells")
hepatocytes_count_dir     = os.path.join(INTERMEDIATE_DIR, "hepatocytes")
hepatocytes_clusters_dir  = os.path.join(INTERMEDIATE_DIR, "hepatocytes_clusters")
hepatocytes_scenic_dir    = os.path.join(INTERMEDIATE_DIR, "hepatocytes_scenic")

# SCENIC databases
scenic_db_dir  = os.path.join(SOURCE_DIR, "scenic_databases")
tf_list        = os.path.join(scenic_db_dir, "allTFs_hg38.txt")
motif_annot    = os.path.join(scenic_db_dir, "motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl")
ranking_dbs    = [
    os.path.join(scenic_db_dir, "hg38_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather"),
    os.path.join(scenic_db_dir, "hg38_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather"),
]

N_HVG = 4000             # number of highly variable genes to select
N_SCENIC_GENES = 1000    # top HV genes to use as SCENIC input per cluster
N_HEATMAP_GENES = 500    # max target genes to show in regulon heatmap (top by variance)
N_TOP_TFS      = 10      # top TFs to show in regulon network
N_TOP_TARGETS  = 10      # top targets per TF to show in regulon network
N_KMEANS_CLUSTERS = 3    # number of k-means clusters for hepatocyte UMAP
